### 현재 없는 변수 
- BF(투구수), PA(타자수), AB(타수), ERR(실책) -> STATIZ에서 가져와야함
- SH(희생타), SF(희생플), GD(병살) -> 타자데이터에서 가져와야함
-  P_WHIP_RT , P2_WHIP_RT, CB_WHIP_RT -> 이부분은 STATIZ에서도 못구하는듯

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import os
import warnings
warnings.filterwarnings(action='ignore')

원래데이터 칼럼들 -> ['G_ID', 'GDAY_DS', 'T_ID', 'VS_T_ID', 'HEADER_NO', 'TB_SC', 'CG_CK',
       'WLS', 'HOLD', 'INN2', 'BF', 'PA', 'AB', 'HIT', 'H2', 'H3', 'HR', 'SB',
       'CS', 'SH', 'SF', 'BB', 'IB', 'HP', 'KK', 'GD', 'WP', 'BK', 'ERR', 'R',
       'ER', 'P_WHIP_RT', 'P2_WHIP_RT', 'CB_WHIP_RT']

In [2]:
data = 'C:/Users/KimMinyoung/Downloads/팀투수_7월_9월22.xlsx'
df = pd.read_excel(data)
temp = df.dropna(); temp

,날짜,초말,상대팀,팀명,더블헤더,팀승,팀무,팀패,승률,기대승률,...,피장타율,피OPS,WHIP,BABIP.1,LOB%.1,ERA.1,RA9-WAR.1,FIP.1,kFIP.1,WAR.1
0,20200801,말,SK,KT,0,1,0,0,1,-,...,0.219,0.454,0.89,0.222,100.0,0.00,0.68,3.16,3.21,0.29
1,20200801,말,KIA,롯데,0,1,0,0,1,-,...,0.412,0.717,1.22,0.333,83.3,3.00,0.27,3.72,3.39,0.16
2,20200801,말,한화,LG,0,1,0,0,1,-,...,0.382,0.732,1.44,0.280,63.5,6.00,0.20,5.27,5.30,0.10
3,20200801,초,삼성,Hero,0,1,0,0,1,-,...,0.353,0.703,1.33,0.308,50.0,6.00,-0.14,3.83,3.91,0.15
4,20200801,초,NC,두산,0,1,0,0,1,-,...,0.556,0.979,2.20,0.371,62.5,8.10,-0.50,6.71,6.76,-0.15
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
263,20200904,초,한화,Hero,0,0,0,1,0,-,...,0.367,0.826,2.12,0.435,58.8,7.88,-0.05,4.47,4.51,0.15
264,20200904,초,KT,SK,1,0,0,2,0,-,...,0.618,1.037,2.04,0.315,63.0,9.18,-0.27,8.46,8.71,-0.31
265,20200904,초,삼성,두산,0,0,0,1,0,-,...,0.676,1.197,3.12,0.412,58.6,12.38,-0.38,9.47,10.08,-0.23
266,20200904,말,NC,LG,0,0,1,0,-,-,...,0.304,0.675,1.42,0.406,75.0,3.75,0.49,2.60,2.33,0.33
267,20200904,초,LG,NC,0,0,1,0,-,-,...,0.391,0.791,1.75,0.406,77.3,3.75,0.55,3.27,3.02,0.48

In [ ]:
new_df = temp[['날짜','팀명','상대팀','더블헤더','초말','완투','팀승','팀무','팀패','홀드','이닝','안타','2루타','3루타','홈런','도루','도실','HBP','고4', '삼진','폭투','보크','실점','자책']]

In [4]:
new_df['WLS'] = np.where(new_df['팀무']==1, 'D', (np.where(new_df['팀승']==1,'W','L')));

In [5]:
new_df = new_df[['날짜','팀명','상대팀','더블헤더','초말','완투','WLS','홀드','이닝','안타','2루타','3루타','홈런','도루','도실','HBP','고4', '삼진','폭투','보크','실점','자책']]

In [6]:
new_df['INN2'] = new_df['이닝']*3

In [7]:
new_df['초말'] = np.where(new_df['초말']=='초','T','B');

In [8]:
new_df = new_df[['날짜','팀명','상대팀','더블헤더','초말','완투','WLS','홀드','INN2','안타','2루타','3루타','홈런','도루','도실','HBP','고4', '삼진','폭투','보크','실점','자책']]

In [9]:
new_name= ['GDAY_DS', 'T_ID', 'VS_T_ID', 'HEADER_NO', 'TB_SC', 'CG_CK','WLS','HOLD','INN2','HIT','H2','H3','HR','SB','CS','BB','IB','KK','WP','BK','R','ER']

In [10]:
new_df.columns = new_name

In [12]:
def set_values(row, value):
    return value[row]
map_dictionary ={"LG":"LG","SK":"SK","NC":"NC","KT":"KT",'롯데' : "LT", "KIA" :"HT", "삼성": "SS","한화":"HH","Hero":"WO","HERO":"WO","두산":'OB'} 
   
new_df['T_ID'] = new_df['T_ID'].map(map_dictionary)
new_df['VS_T_ID'] = new_df['VS_T_ID'].map(map_dictionary)

In [13]:
new_name= ['GDAY_DS', 'T_ID', 'VS_T_ID', 'HEADER_NO', 'TB_SC', 'CG_CK','WLS','HOLD','INN2','HIT','H2','H3','HR','SB','CS','BB','IB','KK','WP','BK','R','ER']

In [14]:
new_df.columns = new_name
new_df

,GDAY_DS,T_ID,VS_T_ID,HEADER_NO,TB_SC,CG_CK,WLS,HOLD,INN2,HIT,...,HR,SB,CS,BB,IB,KK,WP,BK,R,ER
0,20200801,KT,SK,0,B,0,W,0.0,27.0,6.0,...,0.0,0.0,0.0,0.0,0.0,5.0,0.0,0.0,0,0
1,20200801,LT,HT,0,B,0,W,0.0,27.0,9.0,...,1.0,0.0,0.0,0.0,0.0,9.0,0.0,0.0,3,3
2,20200801,LG,HH,0,B,0,W,1.0,27.0,8.0,...,1.0,1.0,0.0,1.0,0.0,8.0,2.0,0.0,6,6
3,20200801,WO,SS,0,T,0,W,1.0,27.0,8.0,...,0.0,0.0,1.0,2.0,0.0,8.0,0.0,0.0,7,6
4,20200801,OB,NC,0,T,0,W,1.0,30.0,15.0,...,2.0,2.0,0.0,0.0,0.0,8.0,0.0,0.0,10,9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
263,20200904,WO,HH,0,T,0,L,0.0,24.0,10.0,...,0.0,0.0,1.0,0.0,0.0,7.0,1.0,0.0,7,7
264,20200904,SK,KT,1,T,0,L,0.0,48.6,22.0,...,5.0,2.0,2.0,0.0,0.0,10.0,0.0,0.0,17,17
265,20200904,OB,SS,0,T,0,L,0.0,24.0,16.0,...,2.0,1.0,0.0,0.0,0.0,3.0,2.0,0.0,12,11
266,20200904,LG,NC,0,B,0,D,0.0,36.0,13.0,...,0.0,3.0,1.0,3.0,1.0,15.0,2.0,0.0,5,5
267,20200904,NC,LG,0,T,0,D,3.0,36.0,13.0,...,0.0,2.0,0.0,1.0,1.0,14.0,1.0,0.0,5,5

In [19]:
new_df.to_csv("C:/Users/KimMinyoung/Desktop/팀투수789.csv")